### ISSUE TITLE
How to handle _FAIL actions

### ISSUE THREAD

**Issue by tjhazel** [Odonno/react-redux-axios-middleware-netcore-example#1]
I see _FAIL constants in the app.ts actions file.  How should we use those?

**state: - updated to better reflect issue**
`export type Root = {
    readonly app: App,
    readonly errors: AnError[],
};`
`export type App = {
    readonly values: { name: string, value: number }[]
};`
`export type AnError = { 
    name: string, value: number 
};`

**action:**
`export type Action =
    {
...
        type: 'APP_GET_VALUES_SUCCESS',
        payload: AxiosResponse
    } | {
        type: 'APP_GET_VALUES_FAIL',
        payload: AxiosError
...
    };`

**reducer:**
```
export const reducer = (state: State.Root = initialState, action: Action): State.Root => {
    switch (action.type) {

        case Actions.GET_VALUES_SUCCESS:
            return {
                ...state,
                app: action.payload.data
                //values: action.payload.data
            };
        case Actions.GET_VALUES_FAIL:
            return {
                ...state,
                errors:  [...state.errors,  { message=action.error.message, code=action.error.code }]      
            };...
```
 Ideally i would map the fail action to a list of errors in the state..my app i have a error message action that ties into App.errors.  Just not sure now to move forward. Any ideas?

Updated to better reflect state type match issue in reducer.

**Comment by Odonno** [comment]
@tjhazel Yes, you can perfectly handle _FAIL action in redux. Your code looks almost good because I found in the docs of redux-axios that an error action should look like this : 

```
{
    type:'OH_NO',
    error: { ... }, //axios error object with message, code, config and response fields
    meta: {
      previousAction: { ... } //action which triggered request
    }
}
```

The `meta` is not mandatory but you can see `payload` property does not exist and so you should use `error` property.

I hope it will fix your problem.

**Comment by tjhazel** [comment]
Thanks for the pointer to AxiosError gets me part way there. I am struggling on how to deal with updating state in the reducer.  The __**SUCCESS**_ call returns values, which maps neatly in the type in the reducer.  

The _**_FAIL**_ maps to a different type, which forces me to change my state type from `State.App` to `State.Root`. I assume this should enable me to access a pier node in the state to store errors.   Not sure this is the correct way to proceed.

I updated the original post to better reflect the issue I am working.

**Comment by Odonno** [comment]
@tjhazel Oh, yes, I see.

When you use Redux, you should create objects for a node that is bound to a reducer/actions. So, in your cases, I would suggest to move your errors array in the `State.App` object so you can handle the changes in the `AppReducer`. 

In Redux, one reducer is linked to one node of your root state. This is not entirely true but it is easier to work that way.

Tell me if you have questions left.
